### ISSUE TITLE
kage data format and magic numbers

### ISSUE THREAD

**Issue by alephpi** [kurgm/kage-engine#1]
Hi Kurgm, thanks for your work.

Could you explain the kage data format briefly? I didn't found them in the doc. By just reading your code, I guess it's in form of 
```
<character>:=<stroke>$...$<stroke>
<stroke>:=<number>:...:<number>
```
but what are those magic numbers mean?

Also I notice you've used numbers in case-switching everywhere, for example [here](https://github.com/kurgm/kage-engine/blob/master/src/stroke.ts#L139-L160), which makes it really tough to understand. I guess they mean certain Buhin class, could you explain?

p.s. I know basic concepts of Buhin(though in Chinese terminology). if you feel more comfortable to refer them in Japanese other than in English(I don't know their proper translation either), just go ahead, I will translate myself.

Thank you in advance.

**Comment by kurgm** [comment]
Hi,

I wrote a detailed explanation of KAGE data format at [Group:サンドボックス@64](https://glyphwiki.org/wiki/Group:%E3%82%B5%E3%83%B3%E3%83%89%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9@64) on GlyphWiki (in Japanese only).
It includes the definitions of the magic numbers.

I hope this helps!

**Comment by kurgm** [comment]
This issue reminded me to move that document to a dedicated article: [GlyphWiki:KAGEデータ仕様](https://glyphwiki.org/wiki/GlyphWiki:KAGE%e3%83%87%e3%83%bc%e3%82%bf%e4%bb%95%e6%a7%98).
Thanks!

**Comment by alephpi** [comment]
Thank you for your advice. It helps a lot. One more question: is there an api that we can input a kage data string and get the rendered svg? I'm doing a python project so it's not easy to embed the js code directly.

**Comment by kurgm** [comment]
Unfortunately, I'm afraid I don't know of any such API...
